version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app
      - /app/node_modules

  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./app:/app
      - /app/node_modules

  auth:
    build: ./auth
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./auth:/auth
      - /auth/node_modules
  
  id:
    build: ./id
    ports:
      - "3002:3002"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./id:/id
      - /id/node_modules

  dashboard:
    build: ./dashboard
    ports:
      - "3003:3003"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./dashboard:/dashboard
      - /dashboard/node_modules

  admin:
    build: ./admin
    ports:
      - "3004:3004"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./admin:/admin
      - /admin/node_modules

  help:
    build: ./help
    ports:
      - "3005:3005"
    environment:
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ./help:/help
      - /help/node_modules
    

  # Répéter pour les autres services...